# NumPy
**NumPy**, short for Numerical Python, is one of the most important foundational packages for numerical computing in Python. Most computational packages providing scientific functionality use NumPy’s array objects as the *lingua franca* for data exchange. Here are some of the things you’ll find in NumPy: 
* ndarray, short for n-dimensional array, an efficient multidimensional array providing fast array-oriented arithmetic operations and flexible *broadcasting* capabilities. 
* Mathematical functions for fast operations on entire arrays of data without having to write loops. 
* Tools for reading/ writing array data to disk and working with memory-mapped files. 
* Linear algebra, random number generation, and Fourier transform capabilities.
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

NumPy by itself does not provide modeling or scientific functionality, but having an understanding of NumPy arrays and array-oriented computing will help you use tools with array-oriented semantics, like pandas, much more effectively.

For most data analysis applications, the main areas of functionality to focus on are: 
* Fast vectorized array operations for data munging and cleaning, subsetting and filtering, transformation, and any other kinds of computations 
* Common array algorithms like sorting, unique, and set operations 
* Efficient descriptive statistics and aggregating/ summarizing data
* Data alignment and relational data manipulations for merging and joining together heterogeneous datasets 
* Expressing conditional logic as array expressions instead of loops with `if-elif-else` branches 
* Group-wise data manipulations (aggregation, transformation, function application)

One of the reasons NumPy is so important for numerical computations in Python is because it is designed for efficiency on large arrays of data. There are a number of reasons for this: 
* NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. NumPy’s library of algorithms written in the C language can operate on this memory without any type checking or other overhead. NumPy arrays also use much less memory than built-in Python sequences. 
* NumPy operations perform complex computations on entire arrays without the need for Python for loops.

In [2]:
# import numpy with standard 'np' naming convention
import numpy as np

In [ ]:
my_arr = np.arange(1000000)    # numpy array
my_list = list(range(1000000)) # vanilla python list

In [11]:
# multiply each sequence by 2 and time results
%time 
for _ in range(10):
    my_arr2 = my_arr * 2

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 6.91 µs


In [12]:
%time 
for _ in range(10):
    my_list2 = [x * 2 for x in my_list]

CPU times: user 6 µs, sys: 1 µs, total: 7 µs
Wall time: 14.1 µs


## Table of Contents
1. [NumPy Arrays](#numpy-arrays)
2. [Generate Random Arrays](#gen-random)

NumPy is a python linear algebra library with bindings to C. It is a foundational package in the PyData ecosystem

## NumPy ndarray: A Multidimensional Array Object
<a id="numpy-arrays"></a>
One of the key features of NumPy is its N-dimensional array object, or ndarray, which is a fast, flexible container for large datasets in Python. Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements.

### Convert Python Lists to NumPy Arrays
You can cast a normal python list into a NumPy array (1-dimensional).

In [15]:
my_list = [1,2,3]

In [16]:
my_list

[1, 2, 3]

In [18]:
data = np.array(my_list)
data

array([1, 2, 3])

An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type. Every array has a `shape`, a tuple indicating the size of each dimension, and a `dtype`, an object describing the *data type* of the array:

In [19]:
data.shape

(3,)

In [20]:
data.dtype

dtype('int64')

### Creating ndarrays
The easiest way to create an array is to use the array function. This accepts any sequence-like object (including other arrays) and produces a new NumPy array containing the passed data.

In [32]:
# convert a python list to an ndarray
data1 = [6,7.5,8,0,1]

arr1 = np.array(data1)

In [33]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

Nested sequences, like lists of equal lengths, are converted into multidimensional arrays

In [34]:
data2 = [[1,2,3],[4,5,6],[7,8,9]]

arr2 = np.array(data2)

In [35]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Unless explicitly specified, `np.array` will try to infer a good data type for the array that it creates.

In [36]:
arr1.dtype

dtype('float64')

In [37]:
arr2.dtype

dtype('int64')

In addition to `np.array`, there are a number of other functions for creating new arrays. As examples, `zeros` and `ones` create arrays of 0s or 1s, respectively, with a given length or shape. `empty` creates an array without initializing its values to any particular value. To create a higher dimensional array with these methods, pass a tuple for the shape:

In [38]:
# creates an ndarray of 0s
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [39]:
# creates a 3x6 matrix of 0s
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [40]:
np.empty((2,3,2))

array([[[  1.49166815e-154,   2.68678960e+154],
        [  2.96439388e-323,   0.00000000e+000],
        [  2.12199579e-314,   5.64233733e-067]],

       [[  5.00725655e-090,   9.30767073e+165],
        [  1.28324011e+160,   3.73319249e-061],
        [  3.99910963e+252,   8.34404858e-309]]])

`arange` is an array-valued version of the built-in Python `range` function:

In [41]:
# creates an ndarray from a range of values
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Array creation functions

(*need to format this better*)

|Function|Description|
|---|---|
|`array`| Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype or explicitly specifying a dtype; copies the input data by default|
|`asarray`| Convert input to ndarray, but do not copy if the input is already an ndarray|
|`arange`| Like the built-in range but returns an ndarray instead of a list|
|`ones`, `ones_like`| Produce an array of all 1s with the given shape and dtype; ones_like takes another array and produces a ones array of the same shape and dtype|
|`zeros`, `zeros_like`| Like ones and ones_like but producing arrays of 0s instead|
|`empty`, `empty_like`| Create new arrays by allocating new memory, but do not populate with any values like ones and zeros|
|`full`, `full_like`| Produce an array of the given shape and dtype with all values set to the indicated “fill value” full_like takes another array and produces a filled array of the same shape and dtype|
|`eye`, `identity`| Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)|

### Data Types for ndarrays
The data type or `dtype` is a special object containing the information (or *metadata*, data about data) the ndarray needs to interpret a chunk of memory as a particular type of data:

In [3]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)

In [4]:
arr1.dtype

dtype('float64')

In [5]:
arr2.dtype

dtype('int32')

dtypes are a source of NumPy’s flexibility for interacting with data coming from other systems.

You can explicitly convert or cast an array from one dtype to another using ndarray's `astype` method:

In [6]:
arr = np.array([1,2,3,4,5])

In [7]:
arr.dtype

dtype('int64')

In [8]:
float_arr = arr.astype(np.float64)

In [9]:
float_arr.dtype

dtype('float64')

### Arithmetic with NumPy Arrays
Arrays are important because they enable you to express batch operations on data without writing any for loops. NumPy users call this *vectorization*.

In [10]:
arr = np.array([[1.,2.,3],[4.,5.,6]])

In [11]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [12]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [13]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

Arithmetic operations with scalars propagate the scalar argument to each element in the array:

In [14]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [15]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

Comparisons between arrays of the same size yeild boolean arrays:

In [16]:
arr2 = np.array([[0.,4.,1],[7.,2.,12]])

In [17]:
arr2

array([[  0.,   4.,   1.],
       [  7.,   2.,  12.]])

In [18]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

### Basic Indexing and Slicing
NumPy array indexing is a rich topic, as there are many ways you may want to select a subset of your data or individual elements.

In [19]:
arr = np.arange(10)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[5]

5

In [22]:
arr[5:8]

array([5, 6, 7])

In [23]:
# broadcasting
arr[5:8] = 12

In [24]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

As you can see, if you assign a scalar value to a slice, as in `arr[ 5: 8] = 12`, the value is propagated (or *broadcasted* henceforth) to the entire selection. An important first distinction from Python’s built-in lists is that array slices are *views* on the original array. This means that the data is not copied, and any modifications to the view will be reflected in the source array. To give an example of this, I first create a slice of `arr`:

In [27]:
def arrays(arr):
    x = np.array(arr)
    return x[-1:0]

In [28]:
arrays([1,2,3,4])

array([], dtype=int64)

### Generate NumPy Arrays
<a id="gen-random"></a>

`np.arange` creates a numpy arange given a start, stop, and optional step size.

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`np.zeros` returns an array of zeros. By passing in a tuple (rows,columns), `np.zeros` will return a matrix of zeros. 

In [8]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [9]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

`np.ones` performs the same operation, except 1's are returned in place of zeros.

In [10]:
np.ones(3)

array([ 1.,  1.,  1.])

In [11]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

`linspace` returns a 1d array of evenly spaced numbers over an interval given a start, stop, and number of points.

In [12]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

`np.eye` creates an identity matrix. An identity matrix is one where the number of rows is the anmes as the number of columns with a diagonal of 1's. 

In [13]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

#### Generate Random Arrays

`rand()` creates an array of uniformly distributed random numbers. Pass in dimensions as arguments rather than as a tuple.

In [14]:
np.random.rand(5)

array([ 0.48600384,  0.32750536,  0.63990712,  0.05145843,  0.90394779])

In [15]:
np.random.rand(5,5)

array([[ 0.97251219,  0.68299719,  0.0505433 ,  0.15607145,  0.45902052],
       [ 0.08518475,  0.84422794,  0.57204182,  0.72273512,  0.94370481],
       [ 0.24704254,  0.48852719,  0.91673711,  0.88172131,  0.89999063],
       [ 0.25877088,  0.23489383,  0.25515035,  0.52207465,  0.18013174],
       [ 0.41915039,  0.61057362,  0.77502397,  0.40995699,  0.86458921]])

The `randn()` function returns values from the standard, normal distribution.

In [16]:
np.random.randn(2)

array([ 0.323097  ,  0.23775821])

In [17]:
np.random.randn(2,4)

array([[ 2.00779223,  0.63100862, -2.0896638 ,  0.64804408],
       [-0.32362771,  0.10813445, -0.69501991,  1.0217047 ]])

`randint()` returns random integers between a low and a high value with an optional thrid argument to specify the number of integers to return. Low is inclusive, high is not.

In [18]:
np.random.randint(1,100)

30

In [19]:
np.random.randint(1,100,5)

array([36, 95,  3, 14, 60])

### Reshaping Arrays

Returns an arry containing the same data with a new shape.

In [20]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr = np.random.randint(0,50,10)
ranarr

array([11, 40, 14,  4, 49, 46, 32, 10, 30, 26])

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Finding Max or Min Values

`max()` and `min()` return the maximum and minimum values of an array (respectively). `argmax()` and `argmin()` return the index values of the max and min values.

In [24]:
ranarr

array([11, 40, 14,  4, 49, 46, 32, 10, 30, 26])

In [25]:
ranarr.max()

49

In [26]:
ranarr.min()

4

In [27]:
ranarr.argmax()

4

In [28]:
ranarr.argmin()

3

`shape` returns the shape of a vector.

In [31]:
arr.shape

(25,)

`dtype` returns the data type of the array

In [32]:
arr.dtype

dtype('int64')

## NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Use brackets an indexing to pull values out of a numpy array.

In [4]:
arr[5]

5

In [5]:
arr[5:7]

array([5, 6])

In [6]:
arr[5:-1]

array([5, 6, 7, 8, 9])

NumPy arrays differ from normal python lists because of their ability to *broadcast*

In [7]:
arr[0:5] = 100

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
slice_of_arr = arr[0:6]

In [10]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [11]:
slice_of_arr[:] = 99

In [12]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [13]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [16]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d[0][0]

5

In [18]:
arr_2d[1]

array([20, 25, 30])

In [19]:
arr_2d[2,1]

40

In [20]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

### Conditional Selection

In [22]:
arr = np.arange(1,11)

In [23]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
bool_arr = arr > 5

In [25]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [26]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [27]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [28]:
arr[arr<3]

array([1, 2])

## Numpy Operations

In [29]:
import numpy as np

In [30]:
arr = np.arange(0,11)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [33]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [35]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [36]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [37]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [38]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [39]:
np.max(arr)

10

In [40]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [41]:
np.log(arr)

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])

## Exercises

In [3]:
# create an array of zeros
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [4]:
# create an array of 10 ones
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
# create an array of 10 fives
np.ones(10) * 5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [6]:
# create an array of integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [8]:
# create an array of even integers between 10 and 50
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [9]:
# create an 3x3 matrix with numbers from 0 to 8
arr = np.arange(0,9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# create a 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [14]:
# generate a random number between 0 and 1
np.random.randn()

0.37680648225372865

In [15]:
# return 25 random numbers sampled from a standard normal dist
np.random.randn(25)

array([ 0.2962741 , -0.25551024,  0.03028987, -0.78464215,  0.55259141,
        0.68113723,  0.31965205, -0.84531173,  1.25640542, -0.48839774,
       -0.93252695, -0.58869998, -0.26802838, -1.01820344,  1.22364064,
       -0.50989295,  1.18025294,  0.7306777 , -0.23742321, -1.34518748,
       -0.99161725,  0.57923734, -1.83298314, -1.15096992,  0.22617052])

In [40]:
#
np.linspace(0.01,1,100).reshape(10,10)

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [21]:
# create an array of 20 linearly spaced points between 1 and 0
np.linspace(0,1,20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [22]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [25]:
mat[3][4]

20

In [32]:
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [33]:
mat[4,0:]

array([21, 22, 23, 24, 25])

In [34]:
mat[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
# get the sum of all the values in mat
mat.sum()

325

In [36]:
# get the stdev of all the values in mat
mat.std()

7.2111025509279782

In [39]:
# get the sum of all the columns in mat
mat.sum(0)

array([55, 60, 65, 70, 75])