# Universal Functions: Fast Element-Wise Array Functions
A universal function, or *ufunc*, is a function that performs element-wise operations on data in ndarrays. You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.

In [2]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

Any ufunc that takes in one array is considered a *urnary* ufunc. Others, like `sum` or `maximum` that take in two arrays are cosidered *binary*.

In [7]:
x = np.random.randn(8)
y = np.random.randn(8)

In [8]:
x

array([ 1.02882767, -1.6297526 ,  0.66189222, -1.02163978, -0.47091332,
        0.7270028 ,  0.53538332, -1.8487845 ])

In [9]:
y

array([ 1.33664396, -0.07355969,  0.35129791, -0.7060075 ,  0.75302498,
       -1.5465961 , -1.10271162, -1.16070981])

In [10]:
np.maximum(x,y)

array([ 1.33664396, -0.07355969,  0.66189222, -0.7060075 ,  0.75302498,
        0.7270028 ,  0.53538332, -1.16070981])

While not common, a ufunc can return multiple arrays. `modf` is one example, a vectorized version of the built-in Python `divmod`; it returns the fractional and integral parts of a floating-point array:

In [11]:
arr = np.random.randn(7) * 5

In [12]:
arr

array([ -3.71613915,   9.48460555,   0.13177395,  13.06977157,
        -3.65117832,  -6.15180036,   4.48593847])

In [13]:
remainder, whole_part = np.modf(arr)

In [14]:
remainder

array([-0.71613915,  0.48460555,  0.13177395,  0.06977157, -0.65117832,
       -0.15180036,  0.48593847])

In [15]:
whole_part

array([ -3.,   9.,   0.,  13.,  -3.,  -6.,   4.])

For a list of ufuncs:
https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html